# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - garageservicemd

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://garagecontainermd.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f8bff42f195548c2aac35c1a71575841 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f0dc9a52120b4699a09714f6c602913f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: garagecontainermd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f8bff42f195548c2aac35c1a71575841 }}/garage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'garageservicemd'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_959e2f0135ce4686bc1d9c580b42a7fd }}
        images: 'garagecontainermd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f8bff42f195548c2aac35c1a71575841 }}/garage:${{ github.sha }}'